### ISSUE TITLE
problem with add exam, add questions etc

### ISSUE THREAD

**Issue by codebit23** [ggsno/Digital-SAT-simulator-client#8]
hello,
It is interesting project. I tried to test it, but it won't create new exam. for example, I added a new, named as temp, then I saw it in drop down button, but when I refreshed Brower, it was gone. could you tell me what is the issue?

Thanks

**Comment by ggsno** [comment]
Hi, thank you for taking interest in my project. Since this project was created a long time ago, I don't remember all the details clearly, but there are a few things I can point out. This is a frontend project, and it needs to be connected to a backend to function fully. While some APIs are mocked, they might not work perfectly. Best of luck!

**Comment by codebit23** [comment]
thanks
